# Generated by Django 4.2.30 on 2026-04-10 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('table_mat', 'Table Mat'), ('shawl', 'Shawl'), ('throw', 'Throw'), ('blanket', 'Blanket'), ('amigurumi', 'Amigurumi'), ('bag', 'Bag'), ('clothing', 'Clothing'), ('accessory', 'Accessory'), ('other', 'Other')], default='other', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('frogged', 'Frogged')], default='completed', max_length=20)),
                ('yarn_brand', models.CharField(blank=True, max_length=100)),
                ('yarn_weight', models.CharField(blank=True, max_length=50)),
                ('yarn_colors', models.JSONField(default=list)),
                ('hook_size', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('has_pattern', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
