# Generated by Django 4.2.30 on 2026-04-10 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('yarn_weight', models.CharField(blank=True, max_length=50)),
                ('hook_size', models.CharField(blank=True, max_length=20)),
                ('gauge', models.CharField(blank=True, max_length=100)),
                ('yarn_amount', models.CharField(blank=True, max_length=100)),
                ('abbreviations', models.JSONField(default=dict)),
                ('materials_list', models.JSONField(default=list)),
                ('instructions', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('sizes_available', models.JSONField(default=list)),
                ('finished_size', models.CharField(blank=True, max_length=100)),
                ('ai_generated', models.BooleanField(default=True)),
                ('ai_model_used', models.CharField(default='claude-sonnet-4-20250514', max_length=100)),
                ('ai_prompt_used', models.TextField(blank=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pattern', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ColourPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mood', models.CharField(choices=[('warm', 'Warm'), ('cool', 'Cool'), ('neutral', 'Neutral'), ('bold', 'Bold'), ('pastel', 'Pastel'), ('earthy', 'Earthy'), ('monochrome', 'Monochrome')], default='neutral', max_length=20)),
                ('colors', models.JSONField(default=list)),
                ('color_names', models.JSONField(default=list)),
                ('ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colour_palettes', to='patterns.pattern')),
            ],
            options={
                'ordering': ['mood', 'name'],
            },
        ),
    ]
