# Generated by Django 4.2.30 on 2026-04-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='chart_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
